# Generated by Django 4.1.5 on 2023-01-24 02:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 24, 10, 52, 24, 960402)),
        ),
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[('Meals', 'Meals'), ('Snacks', 'Snacks'), ('Gifts', 'Gifts'), ('Clothes', 'Clothes'), ('Transport', 'Transport'), ('Entertainment', 'Entertainment'), ("Won't use but still buy", "Won't use but still bye"), ('Misc.', 'Misc.')], max_length=255),
        ),
    ]
