# Generated by Django 4.1.5 on 2023-01-24 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_expense_datetime_alter_expense_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 24, 23, 21, 2, 726049)),
        ),
    ]
