# Generated by Django 4.1.5 on 2023-02-13 06:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_expense_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 13, 6, 1, 20, 64919, tzinfo=datetime.timezone.utc)),
        ),
    ]
