# Generated by Django 4.1.5 on 2023-02-13 16:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_expense_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
